title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: writer
            size: huge
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      more_fields:
        type: fields
        fields:
          cover:
            type: files
            multiple: false
            layout: cards
            image:
              cover: true

