title: Site

columns:
  main:
    width: 2/3
    sections:
      projects:
        type: pages
        parent: site.find('projects')
        template: project
        layout: cards
        image:
          cover: true

  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        templates:
          - home
          - error
          - projects
          - default